### ISSUE TITLE
Does Forge have functionality to pause and continue workflow? 

### ISSUE THREAD

**Issue by swbae31** [microsoft/Forge#18]
An example scenario would be Forge waiting for an User input to continue the workflow.

**Comment by TravisOnGit** [comment]
Great question! I'll discuss two common ways to "pause" a Forge workflow session. If neither of these options sounds appealing, we can brainstorm a Forge feature request to light up this behavior.

**Halt session and restart later:**
A Forge TreeWalkerSession returns from WalkTree if an unhandled exception is thrown. Any exception that is thrown outside of a TreeAction with a RetryPolicy set is considered "unhandled." This includes exceptions thrown from BeforeVisitNode, AfterVisitNode, or while evaluating tree properties such as ActionInput or ShouldSelect statements.

This unhandled exception gets bubbled up to the caller of WalkTree. From there, the application can choose if/when/how to re-walk the session.

Forge's persisted state allows it to continue walking the tree where it left off with [GetCurrentTreeNode()](https://github.com/microsoft/Forge/wiki/How-To:-Use-Forge-in-my-Application#getcurrenttreenode), assuming the application has implemented a [persisted backing store](https://github.com/microsoft/Forge/wiki/ForgeOverview#internal-memory-store) for the IForgeDictionary.

* Example - An application could add some validation checks in BeforeVisitNode, and throw an exception on failure. The application then listens for some ValidationFailedException, and sets up some polling or event-based listener to determine when to trigger a retry of WalkTree.

* Example - An application could add rate limits in BeforeVisitNode, and throw an exception when rate limit is hit, preventing the session from visiting the node. The application then listens for this RateLimitHitException, and triggers a retry of WalkTree after some timeout.

**Await from inside the running session:**
You can also effectively "pause" a session while keeping it running. Instead of throwing an exception like in the first example, await for some trigger there (BeforeVisitNode, AfterVisitNode, ShouldSelect, ForgeAction, etc..). This could be some polling or event-based listener that completes once you wish to continue. Forge will await the task until it completes before continuing on.

* Example - Add a method in [UserContext](https://github.com/microsoft/Forge/wiki/How-To:-Author-a-ForgeTree#using-usercontext-in-your-roslyn-expressions) that awaits until the application gets some response from an end-user. Call this method from your ForgeTree, such as in a ShouldSelect statement.
```yaml
"ShouldSelect": "C#|UserContext.GetUserInput()"
```

* Example - The same logic could also be applied in BeforeVisitNode. Perhaps you have a set of TreeNodes that you know require user input. You could await in BeforeVisitNode to get this user input before continuing on.

* Example - Create a WaitForDelegate ForgeAction that takes a Func as an input and awaits it. Forge natively supports Func properties. Add whatever you wish Forge to await upon in the ActionInput.
```yaml
"Action": "WaitForDelegateAction",
"Input": {
    "BoolDelegateAsync": "C#|(Func<Task<bool>>)(() => { return UserContext.GetUserInput(); })"
}
```

**Comment by swbae31** [comment]
Thanks Travis, this is really helpful. If we were to halt the session every node, and resume using persisted states, would that introduce any latency or resource problems?

**Comment by TravisOnGit** [comment]
You would just need to spin up a new TreeWalkerSession each time, which is quick and cheap.

Also, looking over the code, the only reason you need to initialize a fresh TreeWalkerSession after each WalkTree is the internal cancellation token doesn't get refreshed. I'll add a backlog item to address that so in the future you could call WalkTree multiple times from the same TreeWalkerSession. This would simplify and optimize this retry scenario a bit for stateful applications.
