### ISSUE TITLE
Can Forge re-walk previous nodes? 

### ISSUE THREAD

**Issue by swbae31** [microsoft/Forge#20]
Forge has the GetCurrentTreeNode which fetches the current node. Is there a 'SetCurrentTreeNode' which will set the current node to one of the previous nodes?

Ex) Lets say that a tree has (1),(2),(3),(4),(5) nodes with schema:
(1)->(2)->(3)->(4)->(5)

The current node is (4) and Forge dictionary stores data on the decisions made on (1),(2),(3). 
(1)->(2)->(3)->(4)

At this point, we decide we want to rewalk the tree from node (2), where Forge dictionary will remove any data written from nodes after (2) 
(1)->(2) 

Is behavior like this possible?

**Comment by TravisOnGit** [comment]
I believe I followed up offline when this question was originally asked, but never got around to answering it here.

Forge supports cycles. If you revisit a TreeNode, it's ActionResponses and Intermediates get nullified, and the TreeActions are re-executed. Additionally, the PreviousActionResponse gets populated with the ActionResponse, so your Actions have access to the previous results if they wish.

For your example specifically where data is stored for nodes (1),(2),(3), then we decide to revisit (2). Data for node (2) would be wiped, but data for node (3) would still exist. Perhaps this is fine if node (2) assumes node (3) data does not exist (since it is a child), and once you revisit node (3), it would get wiped at that point. But Forge does not know when you revisit node (2) that it should clean-up any other nodes data.

One last piece of information here is rehydration. A new feature was added in version 1.0.59 to RetryCurrentTreeNodeActions. If you wish to re-execute a TreeNode's Actions upon rehydration (i.e. when first calling WalkTree on a fresh TreeWalkerSession) instead of skipping to ChildSelectors, you can set the RetryCurrentTreeNodeActions flag.

Thanks!
