### ISSUE TITLE
Can we throw custom exception from child in schema?

### ISSUE THREAD

**Issue by kijujjav** [microsoft/Forge#43]
I have an use case where if a specific child selector becomes true, I want to throw an exception. is there a way to do this today?

**Comment by TravisOnGit** [comment]
Hey kijujjav,

Upon selecting the specific child, that child TreeNode could have an Action that throws YourCustomException. The TreeWalkerSession.WalkTree will throw an ActionTimeoutException with YourCustomException as the InnerException.

If you wanted to throw the exception during the child selection itself (without visiting the next node), then you could do that as well. Just throw the exception in the ShouldSelect via the UserContext if the statement is true. The TreeWalkerSession.WalkTree will throw an EvaluateDynamicPropertyException with an InnerException containing YourCustomException in this case. The difference here is that the persisted CurrentTreeNode will not be updated, since you didn't visit the Child node yet.

Let me know if that does/doesn't answer your question.
Thanks,
--Travis

**Comment by TravisOnGit** [comment]
Closing issue. Please re-open if you have any follow-up questions.
